### ISSUE TITLE
More flexible selectors

### ISSUE THREAD

**Issue by Garito** [liftoff/HumanInput#11]
Hi!
I'm trying to use HumanInput but I have a basic problem. Giving this html

```html
<div class="btn btn-default switcher">
  <i class="fa fa-switch"></i>
</div>
```

I'm trying to register a click event like this:
HI.on("click:.switcher", funct);

The funny thing is that it works if I click in the switcher but it doesn't if I click in the fa-switch

Could you explain how to solve this issue?
With bubbling the switcher must recieve the event even if the i was clicked

Is this a bug or something I'm not catching?

Thanks!

PS: what about allowing to use jQuery type of selectors? something like click.switcher > i

**Comment by liftoff** [comment]
This is likely happening because your element doesn't have anything inside of it.  I don't think onclick handlers work when there's nothing inside of *inline* elements.  So a block element would be OK (if it has a size to it via CSS) but not an inline element like `<i></i>` unless you specify in the CSS that it should be `display: block` (I think).

**Comment by liftoff** [comment]
Almost forgot: The reason HumanInput doesn't use jQuery selectors is because I want it to be as standards-based as possible.  Instead of jQuery it uses `document.querySelector()` or `document.querySelectorAll()` which basically negate the need for jQuery (well, it's original purpose anyway).

Fortunately for you I had some foresight in this area and thought some users might want to use jQuery!  So if you want to use jQuery selectors instead of `document.querySelector()` you can just modify `utils.js` from this:

```
    export function getNode(nodeOrSelector) {
        if (typeof nodeOrSelector == 'string') {
            var result = document.querySelector(nodeOrSelector);
            return result;
        }
        return nodeOrSelector;
    };
```

...to something like this:

```
    export function getNode(nodeOrSelector) {
        if (typeof nodeOrSelector == 'string') {
            var result = $(nodeOrSelector);
            return result;
        }
        return nodeOrSelector;
    };
```

There may be a line or two elsewhere that might need minor adjustments as well but I think that's all you really need.

**Comment by Garito** [comment]
I would have to check the code of how I've solve this but will be unfair since I do stuff in a particular way
In this case I was developing a system with maps
The idea was to have a map of the page events for any particular state (default, edition, search) what makes it super easy to manage
Now I'm experimenting with vuejs and I don't have reached the part where I need touch or hotkeys but I will
Probably then I will be using a non jquery aproach (really till now I was using it because of bootstrap but this will not be true per se) so thanks for the information, will be useful very soon
But the important thing here is that I could carry on with my needs so I will use your library when I reach the point
Thanks a lot and I hope I could help here any time soon
