### ISSUE TITLE
Array.from is not defined

### ISSUE THREAD

**Issue by Garito** [liftoff/HumanInput#12]
Hi!
I must to assume that this is a ES6 issue?

Did will solve the problem loading polyfills.js or I must to add anything else?

Thanks!

**Comment by Garito** [comment]
I've investigated more and the error described above is android only
On iOS the error is with window.navigator.userAgent.includes("Mac OS X") being includes undefined

For me it is clear that this is a ES6 issue but I don't understand how to load the polyfills or even if I must load'em at all

**Comment by liftoff** [comment]
This is the type of thing "that shouldn't happen" because polyfills.js is there to solve this exact issue.  Either polyfills.js is missing in your humaninput.js or something is broken in the polyfills themselves (which I doubt because I just copied & pasted them from MDN =).

Are you *sure* the polyfills.js is being included in your .js bundle?

**Comment by liftoff** [comment]
I'm going to close this since I haven't heard back from you.  No one else is reporting this issue (and I can't reproduce it) so I'm going to assume it was just a one-off situation.
