### ISSUE TITLE
Inherited scopes

### ISSUE THREAD

**Issue by lokhmakov** [liftoff/HumanInput#5]
1. I have components inside components
   
   `Designer` have events `designer:alt alt` to show and hide it
   `ServiceTable` have events `designer.service:left`, `designer.service:right`, `designer.service:up`, `designer.service:down`
2. Is there way to enable scope `designer` and `designer.service` in same time or other case how I can do it
3. I have some variants how to develop it, for example put it in one scope and check active ServiceTable or not. But when we have two or more Inherited components (scopes) with same events `left`, `right` or other, they all fire and it's performance drop down a little! )

**Comment by liftoff** [comment]
I'm having trouble understanding your example.  Can you post some code?

Are you trying to have two scopes triggered simultaneously?  That's not how scopes work.  Well, it's not how they were meant to work.  Why not just check the current scope from your bound function (i.e. whatever you attached via `HI.on()`) and dispatch appropriately?

Or you could just bind both scopes simultaneously if you need the same function to be called under both:

```
HI.on(['designer:alt alt', 'designer.service:alt alt'], toggleDesigner);
```

That would make the toggle work in both scopes.  Does that make sense?

**Comment by lokhmakov** [comment]
```
var HI = new window.HumanInput(window, { logLevel: 'DEBUG' })

// COMPONENT DESIGNER

HI.pushScope('designer')

function onLeft() {
  console.log('LEFT')
}

function onRight() {
  console.log('RIGHT')
}

function onService1() {
  // Some doings to exit from service2, etc... if in it
  HI.pushScope('service1')  
  // AFTER THAT I WANT THAT `designer` scope work and `designer.service1` too
}

function onService2() {
  // Some doings to exit from service1, etc... if in it
  HI.pushScope('service2')
  // AFTER THAT I WANT THAT `designer` scope work and `designer.service2` too
}

HI.on('designer:left', onLeft)
HI.on('designer:right', onLeft)
HI.on('designer:1', onService1)
HI.on('designer:2', onService2)

// COMPONENT DESIGNER.SERVICE1

function onService1R() {
  console.log('SERVICE1 PUSH R')
}

HI.on('designer.service1:r', onService1R)


// COMPONENT DESIGNER.SEVICE2

function onService2R() {
  console.log('SERVICE2 PUSH R')
}

HI.on('designer.service2:r', onService2R)
```

**Comment by liftoff** [comment]
For this sort of situation...  Wouldn't it be better to simply create another instance of HumanInput and simply destroy it when no longer in use?  If you need more than one scope to fire at a time I'm not sure how to handle it otherwise because there's no straightforward way to say, "this scope and *these* sub-scopes but not *those* subscopes."

I mean, how do I tell which scopes are enabled or not?  The whole scope system was meant to disable all parent scopes while the child scope was active.  When you're done with that child you pop it out and you're back to normal.  The idea is for simple dialogs and popups and whatnot.

For more sophisticated stuff you can just use multiple instances of HumanInput and enable/disable them on demand.

**Comment by liftoff** [comment]
I'm going to close this comment since I haven't heard back from you.  I'm willing to make changes to add more advanced scopes but I need a better use case/example.
